/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/public/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ping the public API
         * @description Public liveness check for the API surface. Used by the frontend walking skeleton.
         */
        get: operations["public_ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorBody: {
            /** @description Stable machine-readable code, e.g. VALIDATION_ERROR */
            code: string;
            /** @description Human-readable message, safe to show to users */
            message: string;
            details?: components["schemas"]["ErrorDetail"][];
            requestId: string | null;
        };
        ErrorDetail: {
            field: string | null;
            code: string;
            message: string;
        };
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        Ping: {
            service: string;
            version: string;
            environment: string;
            /** Format: date-time */
            time: string;
        };
        PingResponse: {
            data: components["schemas"]["Ping"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    public_ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PingResponse"];
                };
            };
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
